### ISSUE TITLE
how to use this image to scan mounted directory

### ISSUE THREAD

**Issue by travelg** [bfren/docker-clamav#23]
how to use this image to scan mounted directory?
Thank you for nice project.

**Comment by bfren** [comment]
It all depends!  If you mount the directory inside this image, you can use clamav locally, e.g. `docker exec NAME_OF_CLAMAV_CONTAINER clamdscan /path/to/dir`.  (Note the path must be mounted *inside* the container.)

Also you need to wait for `clamav` to download, testm, and load virus definitions first or it won't work - depending on your system this can take a few minutes sometimes.

If the mounted directory is in a different container then that's a little more tricky.  You could use a REST service like (this)[https://github.com/solita/clamav-rest].  Or you could connect to it directly over port 3310.  For that you would need to install the `clamav` package and set up the configuration `clamd.conf` to point to the container running this image.

**Comment by travelg** [comment]
@bfren thanks.
